name: analysis2
channels:
  - conda-forge
  - bioconda
variables:
  CC: /usr/local/bin/gcc-11
dependencies:
  - gmp
  - mpfr
  - pip
  - slim==3.7.1
  - snakemake
  - ldc
  - seaborn
  - pysam
  - htslib
  - scipy
  - numpy
  - matplotlib
  - attrs
  - cython
  - tqdm
  - h5py
  - blas
  - gsl
  - dadi
  - pip:
    - git+https://github.com/popsim-consortium/stdpopsim.git
    - scikit-allel
