cluster: "sbatch -A rgutenk -p high_priority -t {resources.time_min} --mem-per-cpu={resources.mem_mb} -c {resources.cpus} -o logs_slurm/{rule}_{wildcards} -e logs_slurm/{rule}_{wildcards} --mail-type=FAIL --export=ALL,LD_LIBRARY_PATH=/xdisk/rgutenk/xinhuang/software/gsl-2.7/build/lib/"
latency-wait: 180
default-resources: [time_min=60, mem_mb=5000, cpus=1]
