cluster:
        mkdir -p logs_slurm/{rule} &&
        sbatch
                --partition=basic
                --cpus-per-task={resources.cpus}
                --mem-per-cpu={resources.mem_mb}
                --time={resources.time}
                --job-name=smk-{rule}-{wildcards}
                --output=logs_slurm/{rule}/{rule}-{wildcards}-%j

default-resources:
        - time=3000
        - mem_mb=10000
        - cpus=1
latency-wait: 180
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
